networks:
  www:
    external: true

services:
  traefik:
    image: traefik:v2.11.32
    container_name: traefik
    restart: always
    networks:
      - www
    ports:
      - "${INTERFACE}:80:80"
      - "${INTERFACE}:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

      - "traefik.http.routers.dashboard.middlewares=admin"
      - "traefik.http.middlewares.admin.basicauth.users=admin:$$apr1$$qrfvAXtF$$rVPSwcryVS8fV3Cbxrxu0."

    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--log.level=INFO"
      - "--accesslog=true"
      - "--global.sendAnonymousUsage=false"

      - "--providers.docker=true"
      - "--providers.docker.network=www"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
