  version: 1
  
  disable_existing_loggers: false

  formatters:
    standard_formatter:
      format: "%(asctime)s.%(msecs)03d %(levelname)7s %(name)s: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      formatter: standard_formatter
      # class: logging.StreamHandler
      # stream: ext://sys.stdout
      class: mlprod.logs.RichHandler
      rich_tracebacks: True
      show_path: False
      color_system: standard
      width: 200
      level: DEBUG
  loggers:
    mlprod:
      handlers:
        - console
      level: DEBUG
      propagate: false
    httpx:
      handlers:
        - console
      level: ERROR
    root:
      handlers:
        - console
      level: ERROR
      propagate: false
